// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/19/2025, 2:02:22 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/tin/Documents/GitHub/cartoncaps-chat-poc/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tin/Documents/GitHub/cartoncaps-chat-poc/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tin/Documents/GitHub/cartoncaps-chat-poc/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tin/Documents/GitHub/cartoncaps-chat-poc/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tin/Documents/GitHub/cartoncaps-chat-poc/frontend/plugins/**/*.{js,ts,mjs}","/Users/tin/Documents/GitHub/cartoncaps-chat-poc/frontend/composables/**/*.{js,ts,mjs}","/Users/tin/Documents/GitHub/cartoncaps-chat-poc/frontend/utils/**/*.{js,ts,mjs}","/Users/tin/Documents/GitHub/cartoncaps-chat-poc/frontend/pages/index.vue","/Users/tin/Documents/GitHub/cartoncaps-chat-poc/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/tin/Documents/GitHub/cartoncaps-chat-poc/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/tin/Documents/GitHub/cartoncaps-chat-poc/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;